### ISSUE TITLE
如何使用呢？

### ISSUE THREAD

**Issue by zhouJianXXX** [elaninhust/coze-beautify#1]
不知道怎么用，还有一个问题能否只剩下一个preview界面呢？

**Comment by elaninhust** [comment]
你好～感谢关注～🤗
1. 已更新“如何使用”模块
https://github.com/elaninhust/coze-beautify?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

2. 关于直接只剩下 preview 界面的功能，后面有时间的话可以考虑做成自定义选项

**Comment by elaninhust** [comment]
[v1.1.0](https://github.com/elaninhust/coze-beautify/releases/tag/v1.1.0) 已支持默认只显示对话模块，enjoy～
