### ISSUE TITLE
已失效

### ISSUE THREAD

**Issue by zhouJianXXX** [elaninhust/coze-beautify#2]
<img width="1764" alt="image" src="https://github.com/elaninhust/coze-beautify/assets/148297829/a1cc94dc-fd74-4896-8ad8-8974d308acd4">

**Comment by elaninhust** [comment]
thanks for your feedback, I'll dive into it and figure out how to juggle the Multiple agents mode

**Comment by elaninhust** [comment]
fixed in [v1.1.0](https://github.com/elaninhust/coze-beautify/releases/tag/v1.1.0)
