### ISSUE TITLE
Skill栏开关未找到

### ISSUE THREAD

**Issue by Country-If** [elaninhust/coze-beautify#3]
未能找到控制Skill栏的开关，请问如何解决
![image](https://github.com/elaninhust/coze-beautify/assets/62837275/91413bdb-fa87-4445-a3aa-00111fc233f3)

**Comment by elaninhust** [comment]
你右下角的浮窗太多了，正好重叠了

**Comment by Country-If** [comment]
> 你右下角的浮窗太多了，正好重叠了

找到了哈哈，感谢回复
