### ISSUE TITLE
失效了！！！

### ISSUE THREAD

**Issue by wlireland353** [elaninhust/coze-beautify#5]

**Comment by elaninhust** [comment]
官方改版了，我这边兼容一下

**Comment by elaninhust** [comment]
已修复，安装最新版本即可 https://github.com/elaninhust/coze-beautify/releases/tag/v1.1.1

**Comment by wlireland353** [comment]
> 已修复，安装最新版本即可 https://github.com/elaninhust/coze-beautify/releases/tag/v1.1.1

nice
