### ISSUE TITLE
开启后显示空白内容

### ISSUE THREAD

**Issue by tasselx** [elaninhust/coze-beautify#6]
是不是coze的样式代码有修改导致失效了？
![image](https://github.com/elaninhust/coze-beautify/assets/2656142/5937ae12-801f-4044-ac22-505cf74b0acb)

**Comment by elaninhust** [comment]
官方改版了，我这边兼容一下

**Comment by elaninhust** [comment]
已修复，安装最新版本即可 https://github.com/elaninhust/coze-beautify/releases/tag/v1.1.1

**Comment by tasselx** [comment]
> 已修复，安装最新版本即可 https://github.com/elaninhust/coze-beautify/releases/tag/v1.1.1

感谢更新，试过了已经可以了👍
